### ISSUE TITLE
Add support for version 1.19.3 (1.19-R2)

### ISSUE THREAD

**Issue by PWWP** [ErnestoRB/TablistManagerAPI#1]
I propose to add support for minecraft version 1.19.3 - (protocollib version 5.0.0+). Below is a snippet of the error after running the API on version 1.19.3.

`[22:52:55 ERROR]: [TablistManager] Unhandled exception occurred in onPacketSending(PacketEvent) for TablistManager
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib(19).jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218) ~[ProtocolLib(19).jar:?]
        at com.ernestorb.tablistmanager.listener.PacketListener.onPacketSending(PacketListener.java:33) ~[tablistmanager-plugin-1.0.0.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib(19).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib(19).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib(19).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib(19).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib(19).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib(19).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib(19).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib(19).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib(19).jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
        at net.minecraft.server.players.PlayerList.tick(PlayerList.java:967) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1569) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-365]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

**Comment by ErnestoRB** [comment]
Seems like [1.19.3 has changed a lot of packets](https://github.com/dmulloy2/ProtocolLib/issues/2037). Meanwhile I'll make a workaround for supporting it.

**Comment by ErnestoRB** [comment]
@PWWP the new build is here: https://github.com/ErnestoRB/TablistManagerAPI/releases/tag/v1.1.0 
Please tell me if you face some troubles with the new version.

**Comment by PWWP** [comment]
Okay, I'm going to test new release.
